spring.application.name=user

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/goal_tracker_users_db
spring.datasource.username=devuser
spring.datasource.password=dev1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JPA / Hibernate
#spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Spring Security - JWT
jwt.secret=${JWT_SECRET:f157baf4a50cda32a454f3812238cae34d3e0886203165e76668f972e98ae84f}
jwt.issuer=${JWT_ISSUER:service-user}


# KAFKA
spring.kafka.bootstrap-servers=localhost:9092

# CONSUMER
spring.kafka.consumer.group-id=gamification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Pacote confiável para desserialização (SEGURANÇA)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.goaltracker.user.infrastructure.consumer.XpMissionDto

# Tipo padrão caso não venha __TypeId__ no header
spring.kafka.consumer.properties.spring.json.value.default.type=com.goaltracker.user.infrastructure.consumer.XpMissionDto

# PRODUCER
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer